# Generated by Django 4.2.16 on 2024-11-28 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name=30)),
                ('address', models.CharField(verbose_name=50)),
                ('vat_uic_number', models.CharField(max_length=9, unique=True)),
                ('phone_number', models.CharField(max_length=10)),
            ],
        ),
    ]
