# Generated by Django 4.2.16 on 2024-12-09 19:06

import Cleanzy.companies.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='vat_uic_number',
            field=models.CharField(max_length=10, unique=True, validators=[Cleanzy.companies.models.pattern_validator]),
        ),
    ]
