# Generated by Django 4.2.16 on 2024-11-04 13:49

import Cleanzy.products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('products', '0001_initial')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=20)),
                ('product_code', models.CharField(validators=[Cleanzy.products.models.length_validator])),
                ('product_description', models.TextField(blank=True, max_length=300, null=True)),
                ('ph', models.DecimalField(decimal_places=2, max_digits=4)),
                ('product_ingredients', models.TextField(blank=True, max_length=300, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('instructions_for_use', models.TextField()),
            ],
        ),
    ]
