# Generated by Django 4.2.16 on 2024-11-20 10:02

import Cleanzy.products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('code', models.CharField(validators=[Cleanzy.products.models.length_validator])),
                ('description', models.TextField(blank=True, null=True)),
                ('ph', models.DecimalField(decimal_places=2, max_digits=4)),
                ('ingredients', models.TextField(blank=True, max_length=300, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('instructions', models.TextField()),
            ],
        ),
    ]
