# Generated by Django 4.2.16 on 2024-11-22 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='photo',
            field=models.ImageField(default='images/default-product.jpg', upload_to='images/'),
        ),
    ]
